### PR TITLE
[obsolete] Added support for the WT-RFID device

### PR DESCRIPTION
**Pull request by rickardp**
I received my keypad today and I couldn't wait to get it working, so I added some support for the keypad.

I can't take credit for most of the work here, it is based on http://github.com/Inversion-NL/eu.benext

I fixed a few things in the benext code, most important the global system arm/disarm status now works and there is a flow condition for it, otherwise it's pretty much the same.

I did not test all the different features, but basic home/away with multiple users works well.

### CODE REVIEW

**Comment by aartse** [comment]
thank you for your contribution! i'm working on converting all devices to SDK 2 (see the beta channel). because the current SDK 1 is deprecated. the last device i'm working on are the RGB bulbs (whitch is more complex). is it possible that you convert your device driver to SDK 2? so i can merge that in the beta channel. 

when your device and the rgb bulbs are supported in sdk 2, i'll release this to the stable channel.

**Comment by rickardp** [comment]
I might be able to give it a shot if I find some time to do so. From browsing github, I think that this involves changing from the homey-zwavedriver package to the homey-meshdriver? Are there any migration instructions that you follow while migrating? I had a look at the (somewhat scarce) API docs, and they seem to have changed quite a lot.

**Comment by rickardp** [comment]
I got the keypad working with the meshdriver as well, https://github.com/rickardp/athom.zipato

Since I had to rewrite a large part of the code, I took the time to fix the device class/caps and add a mobile UI, so now it should play a lot nicer with the Homey.

I had to remove the gateway mode since I have no feasible way of testing it, and the migration to the meshdriver is intrusive to say the least. 

I need to clean up the code a bit, but I could create another PR with it once I tested it a bit more.

**Comment by aartse** [comment]
nice! i got the rgbw bulbs also working this weekend! i'll test the bulbs this week and create a pull request for the necessary changes in de meshdriver for athom.

**Comment by PatrikGibson** [comment]
I have installed the new version and it works ok except that the flow card for System disarmed never triggers. I can see both on the device and the log that it goes to disarmed but it doesn't trigger the flow. I have a flow that trigger correctly when arming.

**Comment by rickardp** [comment]
Yes, I just noticed that as well. I mist have broken that when migrating. (The device specific card works as an workaround in the meantime).

**Comment by rickardp** [comment]
@PatrikGibson I now committed fixes to the migration issues known by me. Please see if the commit solved the problem

**Comment by rickardp** [comment]
Closing this PR as I was unable to change the source to the SDK2 branch. Further development and discussion can be continued in https://github.com/aartse/athom.zipato/pull/14

**Pull request closed without merging**
